FROM ubuntu:22.04

ARG PREFIX=/usr/local

#Prequisite packages to begin getting files
RUN apt update && apt install -y wget git python3-pip cmake

#Aquire and install ROCm
RUN wget http://artifactory-cdn.amd.com/artifactory/list/amdgpu-deb/amdgpu-install-internal_6.3-22.04-1_all.deb
RUN apt install -y ./amdgpu-install-internal_6.3-22.04-1_all.deb
RUN amdgpu-install --usecase=rocm -y 

#Adjust final path for ability to use rocm components
ENV PATH=$PATH:/opt/rocm/bin/
